apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scibite-ingress
  annotations:
    kubernetes.io/namespace: {{ .Values.namespace }}
    {{- if .Values.external_access }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    {{- else }}
    alb.ingress.kubernetes.io/scheme: internal
    {{- end }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: {{ .Values.tags }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443},{"HTTP": 80}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ingress_cidrs }}
    {{- if .Values.lb_log_s3_bucket }}
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket={{ .Values.lb_log_s3_bucket }},access_logs.s3.prefix={{ .Values.lb_log_prefix }}
    {{- end }}
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /termite*
            pathType: ImplementationSpecific
            backend:
              service:
                name: termite
                port:
                  number: 9090